version: '3'
services:
  dev-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nest_playground
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - nestplayground
networks:
  nestplayground: